// variables.config.js

// Export Environment Variables
import dotenv from 'dotenv'
dotenv.config()

export const {
  PORT,
  JWT_SECRET,
  JWT_EXPIRATION,
  DATABASE,
  DB_PORT,
  HOST_DATABASE,
  PASSWORD_DATABASE,
  USER_DATABASE,
  DATABASE_DEV,
  DATABASE_TEST,
  DB_PORT_DEV,
  HOST_DATABASE_DEV,
  PASSWORD_DATABASE_DEV,
  USER_DATABASE_DEV,
  GMAIL_USER,
  GMAIL_PASS,
  NODE_ENV,
  REDIS_PASS,
  REDIS_USER,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASS_DEV,
  REDIS_USER_DEV,
  REDIS_HOST_DEV,
  REDIS_PORT_DEV,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  S3_BUCKET_NAME,
  ADMIN_GMAIL,
  ADMIN_ROLE,
  ADMIN_NAME,
  ADMIN_PASSWORD_TEST,
  MICROSOFT_GRAPH_API
} = process.env
