name: Node.js API REST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          ADMIN_GMAIL: ${{ secrets.ADMIN_GMAIL }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_PASSWORD_TEST: ${{ secrets.ADMIN_PASSWORD_TEST }}
          ADMIN_ROLE: ${{ secrets.ADMIN_ROLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_TEST: ${{ secrets.DATABASE_TEST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          HOST_DATABASE: ${{ secrets.HOST_DATABASE }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MICROSOFT_GRAPH_API: ${{ secrets.MICROSOFT_GRAPH_API }}
          PASSWORD_DATABASE: ${{ secrets.PASSWORD_DATABASE }}
          PORT: ${{ secrets.PORT }}
          REDIS_HOST_TEST: ${{ secrets.REDIS_HOST_TEST }}
          REDIS_PASS_TEST: ${{ secrets.REDIS_PASS_TEST }}
          REDIS_PORT_TEST: ${{ secrets.REDIS_PORT_TEST }}
          REDIS_USER_TEST: ${{ secrets.REDIS_USER_TEST }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          USER_DATABASE: ${{ secrets.USER_DATABASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm test  # Ejecuta tus pruebas aquí

      - name: Show date and time
        run: date

      - name: Send email notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://${{ secrets.SMTP_USER }}:${{ secrets.SMTP_PASSWORD }}@${{ secrets.SMTP_SERVER }}:${{ secrets.SMTP_PORT }}
          subject: 'CI Notification: All Tests Passed'
          to: ${{ secrets.NOTIFICATION_EMAIL }} 
          from: services@isalegal.app
          body: |
            All tests have passed successfully in the Isa Legal API REST CI workflow.

    concurrency:
      group: "ci-${{ github.ref }}"
      cancel-in-progress: true
