name: Node.js API REST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Show date and time
        run: date

      - name: Send email notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://${{ secrets.SMTP_USER }}:${{ secrets.SMTP_PASSWORD }}@${{ secrets.SMTP_SERVER }}:${{ secrets.SMTP_PORT }}
          subject: 'CI Notification: All Tests Passed successfully'
          to: ${{ secrets.NOTIFICATION_EMAIL }} 
          from: services.isalegal.app
          body: |
            All tests have passed successfully in the Isa Legal API REST CI workflow.

    concurrency:
      group: "ci-${{ github.ref }}"
      cancel-in-progress: true
