name: Node.js API REST

on:
  push:
    branches: [ "main" ]

jobs:
  show-date-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show date and time
        run: date
